### ISSUE TITLE
What is the purpose of echoing the SHA to the _meta folder?

### ISSUE THREAD

**Issue by ghost** [do-community/example-doctl-action#14]
The workflow has the following step:

echo $GITHUB_SHA > $GITHUB_WORKSPACE/site/_meta

What is the purpose of this? Is it used for any particular reason?

**Comment by andrewsomething** [comment]
Hey @waltdizzy,

There is no requirement to do that. I just find it useful to know what commit of the site is deployed live and found this to be a quick way to do that. Of course there are a lot of ways you can accomplish that.
