### ISSUE TITLE
[ERROR] No matches for kind "Deployment"

### ISSUE THREAD

**Issue by guilhermelionzo** [do-community/example-doctl-action#6]
Hi there,

I'm trying to follow the repository tutorial, but I received this error:

```
service/static-example-service created
error: unable to recognize "/home/runner/work/example-doctl-action/example-doctl-action/config/deployment.yml": no matches for kind "Deployment" in version "apps/v1beta1"
##[error]Process completed with exit code 1.
```

Could you guys help me?

**Comment by andrewsomething** [comment]
Unfortunately, in Kubernetes 1.16, the Deployments API changed so there are some differences in what the config should look like. This example is running on a previous version. We should flesh out the README with more docs around this. 

I've tested these changes on a 1.16.6 cluster:
```
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: static-example
+  labels:
+    app: static-example
 spec:
   replicas: 1
+  selector:
+    matchLabels:
+      app: static-example
```

Check out these docs for more details:

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment

**Comment by guilhermelionzo** [comment]
Thanks @andrewsomething, It solved my problem.
